#!/usr/bin/env python


# Import the std copy module first, otherwise python goes tarded later on
# if a different std module tries to use the std copy.
import copy

from cairn.copy import copy


if __name__ == '__main__':
	copy.run()
